// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-trails.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_trails_default = defineTool({
  name: "list_my_trails",
  title: "List my trails",
  description: "List the signed-in user's saved GPX trails (id, name, slug, public flag, updated_at).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max trails to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("trails").select("id,name,slug,is_public,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trails: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trail.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_trail_default = defineTool2({
  name: "get_trail",
  title: "Get trail",
  description: "Fetch a single trail by slug (public trails, or any trail owned by the signed-in user).",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Trail slug (from the shareable URL).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("trails").select("id,name,slug,is_public,updated_at,created_at").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Trail not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { trail: data }
    };
  }
});

// src/lib/mcp/tools/delete-trail.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var delete_trail_default = defineTool3({
  name: "delete_trail",
  title: "Delete trail",
  description: "Delete a trail owned by the signed-in user, identified by slug.",
  inputSchema: {
    slug: z3.string().trim().min(1).describe("Slug of the trail to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("trails").delete().eq("slug", slug).eq("user_id", ctx.getUserId()).select("id,slug,name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "No matching trail found for this user." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted trail "${data[0].name}" (${data[0].slug}).` }],
      structuredContent: { deleted: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qlvexocyryyjwvvqohaj";
var mcp_default = defineMcp({
  name: "gpx-trail-flyer-mcp",
  title: "GPX Trail Flyer",
  version: "0.1.0",
  instructions: "Tools for managing the signed-in user's saved GPX trails in GPX Trail Flyer. Use list_my_trails to browse trails, get_trail to inspect one by slug, and delete_trail to remove one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_trails_default, get_trail_default, delete_trail_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
